### PR TITLE
Update dependencies and small cleanups

### PR DESCRIPTION
**Pull request by camdenorrb**
This project is very outdated and in order for me to run it I had to update some dependencies.

Hope it helps :)

### CODE REVIEW

**Comment by techartist** [comment]
@camdenorrb I was able to get the server to run with these changes.  Thank You.  Now I just need instructions on how to run the plugin.

**Comment by camdenorrb** [comment]
@techartist Glad it helped :)

**Comment by CaelumF** [comment]
Thank you @camdenorrb ! Also thanks for the confirmation it works @techartist

**Comment by CaelumF** [comment]
> @camdenorrb I was able to get the server to run with these changes. Thank You. Now I just need instructions on how to run the plugin.

Did you install https://www.figma.com/community/plugin/856651176156241740/Figma-to-Compose ? Can you see the tool window when you right click, go to plugins and then click Figma to compose? You should be able to then select a frame and click "Generate", if you can't work it out it's probably because it's not working haha, let me know how it goes

**Comment by techartist** [comment]
I got it to work!

**Comment by blackbirdsr71br** [comment]
I have a problen when install this is the error
Variant 'runtimeElements' capability com.beust:klaxon:5.6 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

**Pull request merged**
